class_name Shapes
extends Node2D

# Carve the grid into rectangles. Every rectangle must contain exactly one clue,
# and match what that clue asks for: a square, a tall rectangle, a wide one, or
# any of the three. A clue carrying a number fixes the area as well.
#
# Boards are generated by splitting the grid recursively, so the partition
# always tiles it exactly, and each clue is read off the piece it lands in -
# which means the generated partition is itself a valid solution.

signal exit_to_menu

const MIN_SIZE := 5
const MAX_SIZE := 8
const BOARD_PX := 440.0
const ORIGIN := Vector2(80, 200)

const SQUARE := 0
const TALL := 1
const WIDE := 2
const ANY := 3

# A one-cell piece is a freebie, not a puzzle, so never cut one.
const MIN_AREA := 2

const COLORS := [
	Color("f2b705"), Color("46ac5c"), Color("3d8be0"), Color("f0822f"),
	Color("8f5fc0"), Color("28c2c2"), Color("e069a8"), Color("ff3b30"),
	Color("9b9790"), Color("6fae4f"), Color("d46fb0"), Color("4f9fd4"),
]

var size := MIN_SIZE
var level := 1
var clues := []               # [{cell: Vector2i, kind: int, area: int}]
var solution := []            # [{rect: Rect2i, clue: int}] - the reference tiling
var regions := []             # [{rect: Rect2i, clue: int}] - what the player laid
var cover := []               # cover[row][col] -> index into regions, or -1

var cursor := Vector2i.ZERO
var anchor := Vector2i(-1, -1)
var dragging := false
var solved := false
var message := ""
var message_timer := 0.0
var seeds := Seeds.Entry.new("shapes")


func _ready() -> void:
	new_game()


func new_game() -> void:
	level = 1
	_start_level()


func _start_level() -> void:
	size = clampi(MIN_SIZE + (level - 1) / 3, MIN_SIZE, MAX_SIZE)
	seed(seeds.level_seed(level))
	_generate()
	regions = []
	_rebuild_cover()
	cursor = Vector2i.ZERO
	anchor = Vector2i(-1, -1)
	dragging = false
	solved = false
	message = ""
	queue_redraw()


func cell_px() -> float:
	return BOARD_PX / float(size)


# --- Generation ---------------------------------------------------------------

func _split_options(rect: Rect2i, vertical: bool) -> Array[int]:
	# Cut positions where *both* halves still clear MIN_AREA. With a one-cell
	# thickness that rules out slicing off a single square.
	var out: Array[int] = []
	var span: int = rect.size.x if vertical else rect.size.y
	var thickness: int = rect.size.y if vertical else rect.size.x
	for at in range(1, span):
		if at * thickness >= MIN_AREA and (span - at) * thickness >= MIN_AREA:
			out.append(at)
	return out


func _split(rect: Rect2i, out: Array) -> void:
	var area: int = rect.size.x * rect.size.y
	var v_options := _split_options(rect, true)
	var h_options := _split_options(rect, false)

	# Stop early sometimes so pieces come in a range of sizes.
	if (v_options.is_empty() and h_options.is_empty()) or (area <= 6 and randf() < 0.45):
		out.append(rect)
		return

	var vertical := not v_options.is_empty()
	if not v_options.is_empty() and not h_options.is_empty():
		vertical = rect.size.x > rect.size.y or (rect.size.x == rect.size.y and randi() % 2 == 0)

	if vertical:
		var at: int = v_options[randi() % v_options.size()]
		_split(Rect2i(rect.position, Vector2i(at, rect.size.y)), out)
		_split(Rect2i(rect.position + Vector2i(at, 0), Vector2i(rect.size.x - at, rect.size.y)), out)
	else:
		var at2: int = h_options[randi() % h_options.size()]
		_split(Rect2i(rect.position, Vector2i(rect.size.x, at2)), out)
		_split(Rect2i(rect.position + Vector2i(0, at2), Vector2i(rect.size.x, rect.size.y - at2)), out)


func kind_of(rect: Rect2i) -> int:
	if rect.size.x == rect.size.y:
		return SQUARE
	return WIDE if rect.size.x > rect.size.y else TALL


func _generate() -> void:
	var pieces: Array = []
	_split(Rect2i(Vector2i.ZERO, Vector2i(size, size)), pieces)

	# Harder levels hide more of the help: fewer exact shapes, fewer numbers.
	var any_chance: float = clampf(0.10 + level * 0.03, 0.10, 0.40)
	var number_chance: float = clampf(0.65 - level * 0.03, 0.25, 0.65)

	clues = []
	solution = []
	for piece in pieces:
		var r: Rect2i = piece
		var kind: int = ANY if randf() < any_chance else kind_of(r)
		var area: int = 0
		if randf() < number_chance:
			area = r.size.x * r.size.y
		# A clue that says nothing at all is no clue, so give it its shape back.
		if kind == ANY and area == 0:
			kind = kind_of(r)
		var cell := r.position + Vector2i(randi() % r.size.x, randi() % r.size.y)
		clues.append({"cell": cell, "kind": kind, "area": area})
		solution.append({"rect": r, "clue": clues.size() - 1})


# --- Board state ---------------------------------------------------------------

func _rebuild_cover() -> void:
	cover = []
	for r in size:
		var row := []
		row.resize(size)
		row.fill(-1)
		cover.append(row)
	for i in regions.size():
		var rect: Rect2i = regions[i].rect
		for y in range(rect.position.y, rect.end.y):
			for x in range(rect.position.x, rect.end.x):
				cover[y][x] = i


func clue_at(cell: Vector2i) -> int:
	for i in clues.size():
		if clues[i].cell == cell:
			return i
	return -1


func clues_inside(rect: Rect2i) -> Array[int]:
	var found: Array[int] = []
	for i in clues.size():
		var c: Vector2i = clues[i].cell
		if c.x >= rect.position.x and c.x < rect.end.x and c.y >= rect.position.y and c.y < rect.end.y:
			found.append(i)
	return found


func check(rect: Rect2i) -> String:
	# Returns "" when the rectangle is legal, or the reason it isn't.
	if rect.size.x <= 0 or rect.size.y <= 0:
		return "EMPTY"
	if rect.position.x < 0 or rect.position.y < 0 or rect.end.x > size or rect.end.y > size:
		return "OFF THE BOARD"

	for y in range(rect.position.y, rect.end.y):
		for x in range(rect.position.x, rect.end.x):
			if cover[y][x] != -1:
				return "OVERLAPS A SHAPE"

	var found := clues_inside(rect)
	if found.is_empty():
		return "NO CLUE INSIDE"
	if found.size() > 1:
		return "TWO CLUES INSIDE"

	var clue: Dictionary = clues[found[0]]
	if clue.area > 0 and clue.area != rect.size.x * rect.size.y:
		return "MUST COVER %d SQUARES" % clue.area
	if clue.kind != ANY and kind_of(rect) != clue.kind:
		match clue.kind:
			SQUARE: return "MUST BE A SQUARE"
			TALL: return "MUST BE TALLER THAN WIDE"
			WIDE: return "MUST BE WIDER THAN TALL"
	return ""


func place(rect: Rect2i) -> bool:
	var why := check(rect)
	if why != "":
		message = why
		message_timer = 2.0
		queue_redraw()
		return false
	regions.append({"rect": rect, "clue": clues_inside(rect)[0]})
	_rebuild_cover()
	message = ""
	_check_solved()
	queue_redraw()
	return true


func remove_at(cell: Vector2i) -> bool:
	if cell.x < 0 or cell.x >= size or cell.y < 0 or cell.y >= size:
		return false
	var idx: int = cover[cell.y][cell.x]
	if idx == -1:
		return false
	regions.remove_at(idx)
	_rebuild_cover()
	solved = false
	queue_redraw()
	return true


func filled_cells() -> int:
	var n := 0
	for r in size:
		for c in size:
			if cover[r][c] != -1:
				n += 1
	return n


func _check_solved() -> void:
	# Every clue is satisfied by construction when it is placed, so the board is
	# finished as soon as the rectangles cover it.
	if filled_cells() != size * size:
		return
	solved = true
	Scores.submit_high("shapes", level)


# --- Input ---------------------------------------------------------------------

func cell_at(point: Vector2) -> Vector2i:
	var local := point - ORIGIN
	return Vector2i(int(floor(local.x / cell_px())), int(floor(local.y / cell_px())))


func rect_between(a: Vector2i, b: Vector2i) -> Rect2i:
	var top_left := Vector2i(min(a.x, b.x), min(a.y, b.y))
	var bottom_right := Vector2i(max(a.x, b.x), max(a.y, b.y))
	return Rect2i(top_left, bottom_right - top_left + Vector2i.ONE)


func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventMouseButton:
		var mb := event as InputEventMouseButton
		var cell := cell_at(get_local_mouse_position())
		if mb.button_index == MOUSE_BUTTON_RIGHT and mb.pressed:
			remove_at(cell)
			return
		if mb.button_index != MOUSE_BUTTON_LEFT:
			return
		if mb.pressed:
			if cell.x < 0 or cell.x >= size or cell.y < 0 or cell.y >= size:
				return
			if cover[cell.y][cell.x] != -1:
				remove_at(cell)       # click a shape to take it back
				return
			anchor = cell
			cursor = cell
			dragging = true
		else:
			if dragging and anchor.x != -1:
				place(rect_between(anchor, cursor))
			anchor = Vector2i(-1, -1)
			dragging = false
		queue_redraw()
		return

	if event is InputEventMouseMotion and dragging:
		var cell := cell_at(get_local_mouse_position())
		cursor = Vector2i(clampi(cell.x, 0, size - 1), clampi(cell.y, 0, size - 1))
		queue_redraw()
		return

	if not (event is InputEventKey) or not event.pressed or event.echo:
		return

	# Seed entry takes keys first, so typing a code can't also drive the game.
	match seeds.handle_key(event as InputEventKey):
		Seeds.Entry.CONSUMED:
			queue_redraw()
			return
		Seeds.Entry.APPLIED:
			new_game()
			queue_redraw()
			return

	match (event as InputEventKey).physical_keycode:
		KEY_ESCAPE:
			exit_to_menu.emit()
		KEY_R:
			_start_level()
		KEY_N:
			regions = []
			_rebuild_cover()
			solved = false
			queue_redraw()
		KEY_BACKSPACE, KEY_X:
			remove_at(cursor)
		KEY_ENTER, KEY_KP_ENTER:
			if solved:
				level += 1
				_start_level()
		KEY_SPACE:
			if solved:
				level += 1
				_start_level()
			elif anchor.x == -1:
				anchor = cursor
				dragging = true
			else:
				place(rect_between(anchor, cursor))
				anchor = Vector2i(-1, -1)
				dragging = false
			queue_redraw()
		KEY_LEFT, KEY_A:
			_move_cursor(Vector2i(-1, 0))
		KEY_RIGHT, KEY_D:
			_move_cursor(Vector2i(1, 0))
		KEY_UP, KEY_W:
			_move_cursor(Vector2i(0, -1))
		KEY_DOWN, KEY_S:
			_move_cursor(Vector2i(0, 1))


func _move_cursor(dir: Vector2i) -> void:
	cursor = Vector2i(clampi(cursor.x + dir.x, 0, size - 1), clampi(cursor.y + dir.y, 0, size - 1))
	queue_redraw()


func _process(delta: float) -> void:
	if message_timer > 0.0:
		message_timer = maxf(message_timer - delta, 0.0)
		if message_timer == 0.0:
			message = ""
		queue_redraw()


# --- Drawing -------------------------------------------------------------------

func _rect_px(rect: Rect2i) -> Rect2:
	var s := cell_px()
	return Rect2(ORIGIN + Vector2(rect.position) * s, Vector2(rect.size) * s)


func _draw() -> void:
	var s := cell_px()
	var board := Rect2(ORIGIN, Vector2(BOARD_PX, BOARD_PX))
	draw_rect(board, Blocks.PAPER_SUNK)

	for i in range(1, size):
		draw_line(ORIGIN + Vector2(i * s, 0), ORIGIN + Vector2(i * s, BOARD_PX), Blocks.GRID_LINE)
		draw_line(ORIGIN + Vector2(0, i * s), ORIGIN + Vector2(BOARD_PX, i * s), Blocks.GRID_LINE)

	# Placed shapes
	for i in regions.size():
		var rect := _rect_px(regions[i].rect).grow(-3)
		var col: Color = COLORS[regions[i].clue % COLORS.size()]
		draw_rect(rect, col)
		Blocks.outline(self, rect, col.lightened(0.35), 2.0)

	# The rectangle being dragged out
	if dragging and anchor.x != -1:
		var pending := rect_between(anchor, cursor)
		var ok := check(pending) == ""
		var px := _rect_px(pending).grow(-3)
		draw_rect(px, (Blocks.INK if ok else Blocks.RED) * Color(1, 1, 1, 0.25))
		Blocks.outline(self, px, Blocks.INK if ok else Blocks.RED, 2.0)

	# Clues sit on top of whatever covers them
	for i in clues.size():
		_draw_clue(clues[i], s)

	if not solved:
		var cr := Rect2(ORIGIN + Vector2(cursor) * s, Vector2(s, s))
		Blocks.outline(self, cr.grow(-2), Blocks.INK, 2.0)

	Blocks.outline(self, board.grow(2), Blocks.INK, 1.0)
	_draw_hud()
	_draw_legend()

	if solved:
		Blocks.banner(self, Main.DESIGN_SIZE.x, "FILLED", "ENTER FOR LEVEL %d" % (level + 1))


func _draw_clue(clue: Dictionary, s: float) -> void:
	var center: Vector2 = ORIGIN + (Vector2(clue.cell) + Vector2(0.5, 0.5)) * s
	var covered: bool = cover[clue.cell.y][clue.cell.x] != -1
	var ink: Color = Blocks.PAPER if covered else Blocks.INK

	# A little glyph of the shape the clue is asking for.
	var w := s * 0.30
	var h := s * 0.30
	match clue.kind:
		TALL:
			w = s * 0.20
			h = s * 0.34
		WIDE:
			w = s * 0.34
			h = s * 0.20
	var box := Rect2(center - Vector2(w, h) * 0.5 - Vector2(0, s * 0.12), Vector2(w, h))

	if clue.kind == ANY:
		# Dashed outline: any of the three will do.
		var step := 4.0
		var x := box.position.x
		while x < box.end.x:
			draw_rect(Rect2(x, box.position.y, min(step * 0.55, box.end.x - x), 2.0), ink)
			draw_rect(Rect2(x, box.end.y - 2.0, min(step * 0.55, box.end.x - x), 2.0), ink)
			x += step
		var y := box.position.y
		while y < box.end.y:
			draw_rect(Rect2(box.position.x, y, 2.0, min(step * 0.55, box.end.y - y)), ink)
			draw_rect(Rect2(box.end.x - 2.0, y, 2.0, min(step * 0.55, box.end.y - y)), ink)
			y += step
	else:
		Blocks.outline(self, box, ink, 2.0)

	if clue.area > 0:
		var label := str(clue.area)
		var dims := Blocks.font().get_string_size(label, HORIZONTAL_ALIGNMENT_LEFT, -1, 16)
		draw_string(Blocks.font(), Vector2(center.x - dims.x * 0.5, center.y + s * 0.34),
			label, HORIZONTAL_ALIGNMENT_LEFT, -1, 16, ink)


func _draw_hud() -> void:
	var x := ORIGIN.x

	Blocks.text(self, Vector2(x, 108), "SHAPES", 34, Blocks.INK)
	Blocks.rule(self, Vector2(x, 122), BOARD_PX, Blocks.RED, 3.0)

	Blocks.stat(self, Vector2(x, 150), "LEVEL", str(level), 24)
	Blocks.stat(self, Vector2(x + 110, 150), "SHAPES", "%d/%d" % [regions.size(), clues.size()], 24)
	Blocks.stat(self, Vector2(x + 240, 150), "FILLED", "%d%%" % int(100.0 * filled_cells() / (size * size)), 24)
	if Scores.has("shapes"):
		Blocks.stat(self, Vector2(x + 350, 150), "BEST", "LVL %d" % int(Scores.get_best("shapes")), 24)
	Blocks.tracked(self, Vector2(x, 192), "SEED  " + seeds.label(), 11, Blocks.INK_MID)

	if message != "":
		Blocks.tracked(self, Vector2(x, 186), message, 11, Blocks.RED)


func _draw_legend() -> void:
	var x := ORIGIN.x
	var y := ORIGIN.y + BOARD_PX + 26.0
	Blocks.rule(self, Vector2(x, y - 18), BOARD_PX, Blocks.INK, 1.0)
	Blocks.tracked(self, Vector2(x, y), "EVERY SHAPE HOLDS ONE CLUE - A NUMBER FIXES ITS AREA", 10, Blocks.INK_FAINT)

	var items := [["SQUARE", SQUARE], ["TALL", TALL], ["WIDE", WIDE], ["ANY", ANY]]
	var lx := x
	for item in items:
		var w := 12.0
		var h := 12.0
		if item[1] == TALL:
			w = 8.0
			h = 14.0
		elif item[1] == WIDE:
			w = 14.0
			h = 8.0
		var box := Rect2(lx, y + 16.0, w, h)
		Blocks.outline(self, box, Blocks.INK_FAINT, 1.0)
		Blocks.tracked(self, Vector2(lx + 20.0, y + 27.0), item[0], 10, Blocks.INK_FAINT)
		lx += 108.0

	var cy := y + 48.0
	for line in [
		"DRAG OUT A RECTANGLE - CLICK ONE AGAIN TO TAKE IT BACK",
		"N  CLEAR        R  NEW BOARD        S  SEED        ESC  MENU",
	]:
		Blocks.tracked(self, Vector2(x, cy), line, 10, Blocks.INK_FAINT)
		cy += 16
